### ISSUE TITLE
News Title are not responsive

### ISSUE THREAD

**Issue by raj4477** [raj4477/the-news-nation#1]
News Title i.e the containers which contain the Article, are not responsive.
Although some sort of media query is used.

**Comment by raj4477** [comment]
### Solved
Added the grid property in the main div of the site and added the name of the source of the Article in the Title.

**Follow the below link to check out the new features**
https://the-news-nation.herokuapp.com
```css
.main{
    margin-top: 50px;
    display: grid;
    gap: 30px;
    grid-template-columns: repeat(auto-fill, minmax(300px,1fr));
    
}
```
